# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Webcord workspace 2
windowrule = workspace 2 silent, ^(.*webcord.*)$

# EasyEffects workspace 8
windowrule = workspace 8 silent, ^(.*easyeffects.*)$
