# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Webcord workspace 2
windowrule = workspace 2 silent, ^(.*webcord.*)$

# EasyEffects workspace 10
windowrule = workspace 10 silent, ^(.*easyeffects.*)$

# Thunderbird workspace 3
windowrule = workspace 3 silent, ^(.*thunderbird.*)$
